jenkinsci/hashicorp-vault-plugin

src/main/java/com/datapipe/jenkins/vault/MaskingConsoleLogFilter.java, src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java, src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperTest.java
The vault plugin should mask any secrets obtained through it from the build login [see JIRA Issue](https://issues.jenkins-ci.org/browse/JENKINS-39383). This is already done by the regular jenkins credentials binding plugin - implementation is therefore heavily inspired by how it is done [there](https://github.com/jenkinsci/credentials-binding-plugin/blob/master/src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java#L151).
**Important:** I was not able to run the tests, as it requires a properly initialized local Vault Instance. I would propose to rather mock the real Vault Instance for the Unit Tests to make them not only faster but also easier to run for contributors. Also, my change is actually breaking the test as the test asserts echo'ed output in the log.
=> Automatically mask credentials from build log

src/main/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilter.java
Our jobs are failing (and producing, as expected, no output) with:
```
Executor threw an exception
java.lang.NullPointerException
at com.datapipe.jenkins.vault.log.MaskingConsoleLogFilter$2.compare(MaskingConsoleLogFilter.java:66)
at com.datapipe.jenkins.vault.log.MaskingConsoleLogFilter$2.compare(MaskingConsoleLogFilter.java:63)
at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
at java.util.TimSort.sort(TimSort.java:220)
at java.util.Arrays.sort(Arrays.java:1512)
at java.util.ArrayList.sort(ArrayList.java:1454)
at java.util.Collections.sort(Collections.java:175)
at com.datapipe.jenkins.vault.log.MaskingConsoleLogFilter.getPatternStringForSecrets(MaskingConsoleLogFilter.java:63)
at com.datapipe.jenkins.vault.log.MaskingConsoleLogFilter$1.eol(MaskingConsoleLogFilter.java:38) …
```
=> Filter nulls from secret list

pom.xml, src/main/java/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredentialBinding.java, src/main/java/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredentialBindings.java
AppRoleCredentialsBinding exports VAULT_ADDR and VAULT_TOKEN variables to pipeline environment.
withCredentials([[
$class: 'VaultAppRoleCredentialBinding',
credentialsId: 'approle',
vaultAddr: 'http://vault:8200'
]]) {
sh 'echo token=$VAULT_ADDR'
sh 'echo token=$VAULT_TOKEN'
}
The name of the exported variables can be chosen.
withCredentials([[
$class: 'VaultAppRoleCredentialBinding',
addrVariable: 'VA',
tokenVariable: 'VT',
credentialsId: 'approle',
vaultAddr: 'http://vault:8200'
]]) {
sh 'echo token=$VT'
sh 'echo addr=$VA'
}
=> Approle credential binding

pom.xml
Updated BetterCloud's vault-java-driver from 3.1.0 to 4.0.0.  The latest driver now supports Hashicorp Vault 1.0 and important features: KV v2 and namespaces.
I ran mvn test against this after updating to 4.0.0, and there were no errors.
=> Update pom.xml for vault-java-driver 4.0.0

src/main/java/com/datapipe/jenkins/vault/credentials/VaultGCPCredential.java
This will make logging in by GCP more robust, making the plugin
to retry 5 times with interval of 500 miliseconds, before actually
failing.
Signed-off-by: Karol Krawczyk <kkrawczyk@griddynamics.com>
=> Add retries to loginByGCP() method

src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java, src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java, src/main/java/com/datapipe/jenkins/vault/model/VaultSecret.java, src/main/java/com/datapipe/jenkins/vault/model/VaultSecretValue.java, src/main/resources/com/datapipe/jenkins/vault/VaultBuildWrapper/config.jelly, src/main/resources/com/datapipe/jenkins/vault/configuration/FolderVaultConfiguration/config.jelly, src/main/resources/com/datapipe/jenkins/vault/configuration/GlobalVaultConfiguration/config.jelly, src/main/resources/com/datapipe/jenkins/vault/configuration/VaultConfiguration/config.jelly, src/main/resources/com/datapipe/jenkins/vault/model/VaultSecret/config.jelly, src/main/resources/com/datapipe/jenkins/vault/model/VaultSecretValue/help-envVar.html
added symbol `withVault` and improved step generator by using fixEmptyAndTrim
So now it spits out a block like this:
```groovy
withVault(configuration: [vaultUrl: 'https://vault'], vaultSecrets: [[path: '/secret/a', secretValues: [[vaultKey: 'key']]]]) {
// some block
}
```
For `VaultSecretValue` I made `envKey` optional so when it is left empty `vaultKey` will be used for the environment variable. Making the pipeline less verbose
I switched `VaultConfiguration` to an empty constructor
=> Improvements

.idea/codeStyles/Project.xml, pom.xml, src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java, src/main/java/com/datapipe/jenkins/vault/configuration/GlobalVaultConfiguration.java, src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java, src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperWithMockAccessor.java, src/test/java/com/datapipe/jenkins/vault/it/VaultConfigurationIT.java, src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java, src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultTestUtil.java, src/test/resources/com/datapipe/jenkins/vault/jcasc/secrets/pipeline.groovy, src/test/resources/com/datapipe/jenkins/vault/jcasc/secrets/vault.yml, src/test/resources/com/datapipe/jenkins/vault/jcasc/secrets/vaultTest_agent.hcl
Needed to bump credentials plugin to validate credential configuration via configuration-as-code.
Which means I needed to bump Jenkins version.
Bumped optional dependency of configuration-as-code which fixes vault initialization being called too late. :scream:
fixes https://github.com/jenkinsci/configuration-as-code-plugin/issues/967
=> add support for vault agent

src/main/java/com/datapipe/jenkins/vault/credentials/VaultKubernetesCredential.java, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultKubernetesCredential/credentials.jelly
The kubernetes method in the better cloud libraries is really just the JWT backend with a hardcoded path of "kubernetes".
This allows you to specify your own mount path
=> switch to using jwt auth method for kubernetes

README.md, pom.xml, src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultUsernamePasswordCredentialImpl.java, src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java, src/test/java/com/datapipe/jenkins/vault/configuration/VaultConfigurationSpec.java, src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java, src/test/java/com/datapipe/jenkins/vault/util/TestConstants.java, src/test/java/com/datapipe/jenkins/vault/util/VaultTestUtil.java, src/test/resources/com/datapipe/jenkins/vault/util/vaultTest_adminPolicy.hcl
This PR updates vault-java-driver and implements support for prefixPath field (ref https://github.com/BetterCloud/vault-java-driver/pull/189 )
With it, it's now possible to use secrets with a custom prefix (for example `my/custom/prefix/kv/secret1`).
=> Support prefixPath field

README.md, src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAuthenticator.java, src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultKubernetes.java, src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultKubernetesAuthenticator.java, src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java
This PR is based on the work done in #52 and allows to use Kubernetes Service Account while using CasC.
As the other authentication methods, a `CASC_VAULT_KUBERNETES_ROLE` parameter is needed to enable this methods. 
I wasn't able to add tests because we would need to have a Kubernetes instance running to validate the token (or mock something).
=> CasC: allow login by Kubernetes ServiceAccount

src/main/java/com/datapipe/jenkins/vault/credentials/VaultKubernetesCredential.java, src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultKubernetesAuthenticator.java
Hi,
We're using the plugin to inject git credentials into jobs. It works really well, except there seems to be a file descriptor leak somewhere in the code specifically to the kubernetes service account token.
I've created this issue https://issues.jenkins-ci.org/browse/JENKINS-61437
I think the culprit is `Files.lines` because as stated in the documentation https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#lines-java.nio.file.Path-java.nio.charset.Charset- 
>  If timely disposal of file system resources is required, the try-with-resources construct should be used to ensure that the stream's close method is invoked after the stream operations are completed.
All tests pass when running on my machine.
=> Use try-with-resources when reading kubernetes service account token.

README.md, src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java, src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java, src/test/resources/com/datapipe/jenkins/vault/jcasc/secrets/vault.yml
This change makes it's possible to use the full path of secret in the jcasc configuration.  This way multiple secrets with the same key can be used. Resolves #85
=> add full path variables to jcasc secrets

.github/workflows/maven.yml, Jenkinsfile, pom.xml
This enables us to use Jenkins Core BOM when using plugin pom v4
Also allows us to use Jenkins Core that supports java 11 by default.
Cleaned up the pom
=> update jenkins version to 2.164.3

src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultStringCredential.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialBinding.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialImpl.java, src/main/resources/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialBinding/config-variables.jelly, src/main/resources/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialBinding/help.html, src/main/resources/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialImpl/credentials.jelly, src/test/java/com/datapipe/jenkins/vault/it/VaultStringCredentialIT.java
Hi!
Would you please consider for inclusion the following PR that adds VaultStringCredential, i.e. the secret text type of credential fetched from Vault.
I'm trying to move all secrets from Jenkins to Vault and I needed this on several occasions.
Please, let me know if anything in the PR should be different or improved.  I have some doubts about the integration test, but I tried to mimic the existing tests as much as possible.
Thanks,
Josip
=> Add Vault secret text credentials

src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
The Vault build wrapper does not respect the path prefix configuration item.
This PR ensures that the build wrapper with properly use the path prefix.
=> Adding support for prefix path

src/main/java/com/datapipe/jenkins/vault/credentials/VaultGithubTokenCredential.java, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultGithubTokenCredential/credentials.jelly, src/test/java/com/datapipe/jenkins/vault/credentials/VaultGithubTokenCredentialTest.java
Signed-off-by: Dinesh <dineshudt17@gmail.com>
Previously we were using `github` as the mountPath and it is the default value in vault. In this PR, your can choose the custom mount path which is configured in Vault.
I will update the README if this feature make sense. Thanks
=> Able to specify custom mountPath for github token credential

src/main/java/com/datapipe/jenkins/vault/credentials/AbstractAuthenticatingVaultTokenCredential.java, src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpiration.java, src/test/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpirationTest.java
This PR adds the support to store the expiration of the token and use the same token unless it is expired. This will help to reduce number of tokens created by Jenkins Plugin on vault.  This is specially helpful in case of tokens with long TTLs - as getting new token every-time can easily overwhelm the Vault server.
Thanks @dineshba @SrinivasanTarget for help.
=> Support tokens with expiration while fetching secrets #133

.idea/codeStyles/Project.xml, src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java, src/main/java/com/datapipe/jenkins/vault/model/VaultSecretValue.java, src/main/resources/com/datapipe/jenkins/vault/model/VaultSecretValue/config.jelly, src/main/resources/com/datapipe/jenkins/vault/model/VaultSecretValue/help-isRequired.html
Add an optional `required` parameter to VaultSecretValues so that secrets can quietly be empty if `required: false` is set.
Edit: Further explanation
while `failIfNotFound` configuration option exists, this is for handling when a _secret_ is not found. This PR is to more granularly allow optional values within a secret, for example:
```groovy
def secrets = [
[
path: 'some/path/in/vault',
secretValues: [
[envVar: 'MANDATORY_THING', vaultKey: 'mandatoryThing', isRequired: true]
[envVar: 'OPTIONAL_THING', vaultKey: 'optionalThing', isRequired: false],
]
]
]
```
=> Add optional `required` parameter to VaultSecretValue

src/main/java/com/datapipe/jenkins/vault/configuration/FolderVaultConfiguration.java, src/main/java/com/datapipe/jenkins/vault/configuration/GlobalVaultConfiguration.java, src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfigResolver.java, src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java, src/main/java/com/datapipe/jenkins/vault/credentials/VaultCredentialsProvider.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/AbstractVaultBaseStandardCredentials.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultCertificateCredentialsImpl.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultFileCredentialImpl.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultHelper.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultSSHUserPrivateKeyImpl.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialImpl.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultUsernamePasswordCredentialImpl.java, src/main/resources/com/datapipe/jenkins/vault/credentials/common/VaultCertificateCredentialsImpl/credentials.jelly
The modifications I introduced in this pull request are about getting the right vault configuration from the right context, so when I fill in the vault config for a multibranch pipeline then I test the retrieval of my secret from vault by the "Test Vault Secrets retrieval" button, It works while before it always using the global configuration because we were missing the credentials' context when we're looking for the vault configuration.
Now, the "Test Vault Secrets retrieval" button and the pipelines (Jenkinsfile) use the right vault config as they look for it in the right order in the chain (From pipeline => possible parents (folder Item) ==> Jenkins global config).
I also added those lines in: https://github.com/jenkinsci/hashicorp-vault-plugin/pull/195/commits/ae364e20666fdfa3f47598483 …
=> fixing the fallback to get the config to access Vault

src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultGCRLogin.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultGCRLoginImpl.java, src/main/resources/com/datapipe/jenkins/vault/credentials/common/VaultGCRLoginImpl/credentials.jelly, src/main/resources/com/datapipe/jenkins/vault/credentials/common/VaultGCRLoginImpl/help-namespace.html, src/main/resources/com/datapipe/jenkins/vault/credentials/common/VaultGCRLoginImpl/help-path.html, src/main/resources/com/datapipe/jenkins/vault/credentials/common/VaultGCRLoginImpl/help-prefixPath.html, src/test/java/com/datapipe/jenkins/vault/it/VaultGCRLoginIT.java
This adds a credential type that can be used to authenticate with GCR when using `docker.withRegistry()` or the `docker` and `dockerfile` agent types.  I'm not sure if this needs some specific documentation to make its use clear how to use.
This builds on top of changes in #178.
=> Add credential type to authenticate with Google Container Registry

pom.xml, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultHelper.java
Removes the `SecretRetrieve` class that allowed agents to access vault.
=> Ensure vault access only takes place from the controller

src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultSSHUserPrivateKeyBinding.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultSSHUserPrivateKeyImpl.java
SSH private keys should end with a newline. This update ensures that the private
keys returned by the vault SSHUserPrivateKey implementation end with newlines
just like the reference implementation does. If the secret value in vault does not
have a newline it will result in an error when attempting to use the rendered key file:
```
[ssh-agent] Using credentials **** (**** ssh credentials)
[ssh-agent] Looking for ssh-agent implementation...
[ssh-agent]   Exec ssh-agent (binary ssh-agent on a remote machine)
$ ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-fYTrdIvAKCqI/agent.317
SSH_AGENT_PID=319
Running ssh-add (command line suppressed)
Error loading key "/home/jenkins/workspace/tools/test-vault-ssh-key@tmp/private_key_2757282350355641480.key": invalid format
```
Vault users can add a newline to the …
=> Ensure ssh private key ends with newline

README.md, pom.xml, src/main/java/com/datapipe/jenkins/vault/credentials/VaultTokenCredentialBinding.java, src/main/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilter.java, src/test/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilterSpec.java
Use SecretPatterns API introduced in credentials-binding-plugin 1.26. Bumped
the jenkins version and bom import to 2.303.x to pull in the required
plugin dependency version.
Refs: JENKINS-65972
=> [JENKINS-65972] Use SecretPatterns API

src/main/java/com/datapipe/jenkins/vault/credentials/common/AbstractVaultBaseStandardCredentials.java, src/test/java/com/datapipe/jenkins/vault/credentials/common/AbstractVaultBaseStandardCredentialsTest.java
Add `transient` modifier to `AbstractVaultBaseStandardCredentials#context` field. This excludes the ItemGroup context field from serialization when jenkins configuration is saved. This field is injected by VaultCredentialsProvider when credentials are resolved.
Fixes #264
- [x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
=> Exclude credential ItemGroup context from serialization

src/main/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilter.java
Fixes #311, supersedes #309, triggered by https://github.com/jenkinsci/credentials-binding-plugin/pull/260. Implementation is simpler than the `WeakHashMap` trick in https://github.com/jenkinsci/credentials-binding-plugin/pull/28. Not tested other than whatever CI covers.
=> [JENKINS-71788] Fix timing of `SecretPatterns.getAggregateSecretPattern`

src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java, src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperTest.java
This fixes #163 in the way asked for by @jetersen, but also adds a unit test to ensure correct behavior. I chose not to base it on the failIfNotFound flag since access denied shows a configuration issue that should be addressed immediately instead of "I have permissions, but it just doesn't exist" that failIfNotFound is for.
=> Raise exception when access is denied instead of silently failing

src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpiration.java
We have seen issues where a token is attempted to be used and is determined to be valid by the code, but expires before it is actually used. There is a buffer of 2 seconds set in the code, but this is apparently not long enough. Ideally this would be configurable, but for now I would like to extend that buffer to 10 seconds. Tokens will be considered expired if they expire within the next 10 seconds during the check instead of 2 seconds.
This is such a simple change that I decided not to create an issue for it, please let me know if you would like an issue instead.
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
=> Make sure token does not expire within 10 seconds instead of 2

README.md, src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java, src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java, src/main/java/com/datapipe/jenkins/vault/credentials/AbstractAuthenticatingVaultTokenCredential.java, src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredential.java, src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpiration.java, src/main/java/com/datapipe/jenkins/vault/credentials/VaultCredential.java, src/main/resources/com/datapipe/jenkins/vault/configuration/VaultConfiguration/config.jelly, src/main/resources/com/datapipe/jenkins/vault/configuration/VaultConfiguration/help-disableChildPoliciesOverride.html, src/main/resources/com/datapipe/jenkins/vault/configuration/VaultConfiguration/help-policies.html, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredential/credentials.jelly, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredential/help-usePolicies.html, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultAwsIamCredential/credentials.jelly, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultAwsIamCredential/help-usePolicies.html, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultGCPCredential/credentials.jelly, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultGCPCredential/help-usePolicies.html, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultGithubTokenCredential/credentials.jelly, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultGithubTokenCredential/help-usePolicies.html, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultKubernetesCredential/credentials.jelly, src/main/resources/com/datapipe/jenkins/vault/credentials/VaultKubernetesCredential/help-usePolicies.html, src/test/java/com/datapipe/jenkins/vault/VaultAccessorTest.java, src/test/java/com/datapipe/jenkins/vault/credentials/AbstractAuthenticatingVaultTokenCredentialTest.java, src/test/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpirationTest.java, src/test/java/com/datapipe/jenkins/vault/it/VaultConfigurationIT.java
Fixes #214 
This adds support for separating job policies as described in #214. This is inspired by the [Salt integration](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.vault.html) and their usage of per-minion policies. The vault plugin may be configured with optional "policies" that may be templatized with tokens that are unique to the job. This allows more isolation of job permissions in Vault, thereby allowing for more secure Jenkins configurations.
I was able to add most of the logic for this functionality into the expiring credential base class. I also had to separate the cached token value by the list of policies specified so that different lists of policies resulted in new tokens. I have tested this on our Jenkins environment and it has allowed me to …
=> Adds support for using job-specific policies

src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpiration.java
This should fix #323 (as suggested by @jetersen) to prevent serialization of a field that cannot be serialized.
See also #268.
I tested this out locally on a Jenkins instance and didn't see any problems with it, but as I never reproduced the original error, I could use some help from @omehegan to test this out.
```[tasklist]
```
=> Fixes #323 to prevent serialization of token expiry

src/main/java/com/datapipe/jenkins/vault/VaultBindingStep.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultCertificateCredentialsBinding.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialBinding.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultUsernamePasswordCredentialBinding.java, src/test/java/com/datapipe/jenkins/vault/VaultBindingStepWithMockAccessor.java
Annotations for Nonnull, CheckForNull, and several others were proposed for Java as part of dormant Java specification request JSR-305. The proposal never became a part of standard Java.
Jenkins plugins should switch from using JSR-305 annotations to use Spotbugs annotations that provide the same semantics.
The [mailing list discussion](https://groups.google.com/g/jenkinsci-dev/c/uE1wwtVi1W0/m/gLxdEJmlBQAJ) from James Nord describes the affected annotations and why they should be replaced with annotations that are actively maintained.
The ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/replace-jsr-305-annotations/) provides instructions to perform this change.
An [OpenRewrite recipe](https://docs.openrewrite.org/recipes/jenkins/javaxannotationstospotbugs …
=> Replace JSR-305 annotations with spotbugs annotations

src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultSSHUserPrivateKeyImpl.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialImpl.java, src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultUsernamePasswordCredentialImpl.java
Support taking snapshots of Vault secrets to allow them to be used properly on agents.
Have run this locally in combination with jenkinsci/artifactory-artifact-manager-plugin#53 and it works a charm.
=> JENKINS-73398: Support credential snapshots

src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpiration.java
XStream attempts to deserialize all fields in XML files that have a corresponding field in the class, even if it is marked `transient`. This means that #325 did not actually fix the issues described in #323, #324, and #326, which were caused by #223.
This should fix #323, #324, and #326. I tested it manually with a corrupted folder.
=> Rename tokenExpiry field to prevent Folders corruption issues when upgrading from old versions of this plugin

src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpiration.java
It is possible for users who have a `AbstractVaultTokenCredentialWithExpiration` that was created after https://github.com/jenkinsci/hashicorp-vault-plugin/pull/223 and has not been resaved since https://github.com/jenkinsci/hashicorp-vault-plugin/pull/325 to still have a non-null `tokenCache` field on disk (and a non-null `tokenExpiry` field).
As of #336, this causes problems, because the following logic only checks for a non-null `tokenCache` to decide if the transient fields need to be initialized:
https://github.com/jenkinsci/hashicorp-vault-plugin/blob/946b53544a30ed5a2333e2a1abc79b1090d9be45/src/main/java/com/datapipe/jenkins/vault/credentials/AbstractVaultTokenCredentialWithExpiration.java#L110
We need to adjust this logic to check for both `tokenCache` and the newly-renamed …
=> Make sure both tokenCache and tokenExpiryCache are initialized if needed
