- pom.xml
- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
- src/main/java/com/datapipe/jenkins/vault/credentials/VaultTokenCredential.java
- src/main/java/com/datapipe/jenkins/vault/credentials/impl/VaultTokenCredentialImpl.java
- src/main/resources/com/datapipe/jenkins/vault/VaultBuildWrapper/config.jelly
- src/main/resources/com/datapipe/jenkins/vault/VaultBuildWrapper/global.jelly
- src/main/resources/com/datapipe/jenkins/vault/credentials/impl/VaultTokenCredentialImpl/credentials.jelly
- src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperTest.java
The vault token should be stored as a jenkins credential.
This PR might need to be updated when #4 is merged.
> Enhancement: store token as credential

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
> [JENKINS-44163] - Build fails if plugin is enabled for a job without secrets specified

- src/main/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilter.java
Sometimes the whole collection can be null, too.
> avoid npe crash

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
> [JENKINS-48049] Switch to SimpleBuildWrapper for pipeline compatibility

- src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java
- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
- src/main/java/com/datapipe/jenkins/vault/VaultDisposer.java
- src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java
- src/main/java/com/datapipe/jenkins/vault/credentials/VaultCredential.java
- src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperWithMockAccessor.java
- src/test/java/com/datapipe/jenkins/vault/it/VaultConfigurationIT.java
- src/test/java/com/datapipe/jenkins/vault/it/folder/FolderIT.java
This allows for revoking of lease_ids if any are returned from vault.logical.read of secrets
> Revoke lease vault disposer

- README.md
After build and install the latest version of plugin following concerns were seen - missed documentation `how to use` and couples problem with `java.lang.NullPointerException`. This `PR` cover answers on how to fix it.
> Update documentation for KV 2 Engine and backward compatibility

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
> [JENKINS-44704] - support variable expand for vault path

- README.md
hopefully, this is more clarifying @kkalugerov 👍
> simplify pipeline snippet

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
- src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperTest.java
- src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java
fixes https://issues.jenkins-ci.org/browse/JENKINS-59247
Signed-off-by: Michael Sprauer <Michael.Sprauer@sap.com>
> [JENKINS-59247] - fix "Fail if path is not found"

- pom.xml
> use versions from BOM

- src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAppRole.java
- src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAppRoleAuthenticator.java
- src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAuthenticator.java
- src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultAuthenticatorWithExpiration.java
- src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java
- src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultUserPassAuthenticator.java
- src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultUsernamePassword.java
> [JENKINS-59847] - allow login by AppRole mount

- src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java
- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
> [JENKINS-59836] - Do not serialize VaultConfig

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
> fix potential null pointer

- src/main/resources/com/datapipe/jenkins/vault/configuration/VaultConfiguration/config.jelly
> add missing prefix path in jelly

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
> do not mask blank secrets as it garbels logs

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
- src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java
- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultHelper.java
- src/test/java/com/datapipe/jenkins/vault/configuration/VaultConfigurationSpec.java
- src/test/java/com/datapipe/jenkins/vault/it/folder/FolderIT.java
> switch to Boolean for mergable booleans

- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultSSHUserPrivateKeyBinding.java
> Fix ssh user key binding 

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
- src/main/java/com/datapipe/jenkins/vault/configuration/GlobalVaultConfiguration.java
- src/main/java/com/datapipe/jenkins/vault/configuration/VaultConfiguration.java
- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultHelper.java
- src/test/java/com/datapipe/jenkins/vault/it/VaultConfigurationIT.java
- src/test/java/com/datapipe/jenkins/vault/it/folder/FolderIT.java
> Fix defaulting vault engine version inside vault helper

- src/main/java/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredential.java
> fix null approle on readResolve

- src/main/java/com/datapipe/jenkins/vault/credentials/VaultKubernetesCredential.java
- src/test/java/com/datapipe/jenkins/vault/credentials/VaultKubernetesCredentialTest.java
Signed-off-by: Dinesh <dineshudt17@gmail.com>
> Add blankCheck for kubernetes mountPath

- .github/workflows/maven.yml
- Jenkinsfile
- pom.xml
- src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperTest.java
- src/test/java/com/datapipe/jenkins/vault/credentials/AbstractAuthenticatingVaultTokenCredentialTest.java
- src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java
- src/test/java/com/datapipe/jenkins/vault/util/VaultContainer.java
- src/test/java/com/datapipe/jenkins/vault/util/VaultTestUtil.java
> update deps and fix vault test suite

- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultGCRLoginImpl.java
> add context in doTestConnection

- pom.xml
> Bump bom from 1289.v5c4b_1c43511b_ to 1466.v85a_616ea_b_87c

- pom.xml
> Bump bom from 1466.v85a_616ea_b_87c to 1472.vb_65d893c9a_b_6

- src/main/java/com/datapipe/jenkins/vault/credentials/VaultTokenFileCredential.java
> fixes SECURITY-2521

- src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java
> Mark logger of VaultBuildWrapper as transient

- pom.xml
This results into a smaller installation footprint.
```[tasklist]
```
> Replace the fat `aws-java-sdk` plugin with `aws-java-sdk-minimal`

- src/main/resources/com/datapipe/jenkins/vault/credentials/VaultTokenCredentialBinding/config-variables.jelly
fixes #296
Make sure you are opening from a topic/feature/bugfix branch (right side) and not your main branch!
Ensure that the pull request title represents the desired changelog entry
Please describe what you did
Link to relevant issues in GitHub or Jira
Link to relevant pull requests, esp. upstream and downstream changes
Ensure you have provided tests - that demonstrates feature works or fixes the issue
it is fix for https://github.com/jenkinsci/hashicorp-vault-plugin/issues/296
Changed textbox fields from value to default
> fix default values in addrVar and tokenVar UI

- pom.xml
- src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java
- src/main/java/com/datapipe/jenkins/vault/VaultBindingStep.java
- src/main/java/com/datapipe/jenkins/vault/configuration/GlobalVaultConfiguration.java
- src/main/java/com/datapipe/jenkins/vault/credentials/VaultAppRoleCredential.java
- src/main/java/com/datapipe/jenkins/vault/credentials/VaultCredentialsProvider.java
- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultCertificateCredentialsBinding.java
- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultFileCredentialBinding.java
- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultFileCredentialImpl.java
- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultHelper.java
- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultStringCredentialImpl.java
- src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultUsernamePasswordCredentialBinding.java
- src/main/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSource.java
- src/main/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilter.java
- src/test/java/com/datapipe/jenkins/vault/AwsHelperTest.java
- src/test/java/com/datapipe/jenkins/vault/VaultBindingStepWithMockAccessor.java
- src/test/java/com/datapipe/jenkins/vault/VaultBuildWrapperTest.java
- src/test/java/com/datapipe/jenkins/vault/configuration/FolderVaultConfigurationSpec.java
- src/test/java/com/datapipe/jenkins/vault/configuration/VaultConfigurationSpec.java
- src/test/java/com/datapipe/jenkins/vault/it/buildwrapper/CustomCredentialTest.java
- src/test/java/com/datapipe/jenkins/vault/it/buildwrapper/SSLTest.java
- src/test/java/com/datapipe/jenkins/vault/jcasc/secrets/VaultSecretSourceTest.java
- src/test/java/com/datapipe/jenkins/vault/log/MaskingConsoleLogFilterSpec.java
- src/test/java/com/datapipe/jenkins/vault/util/VaultTestUtil.java
Jenkins 2.479.3 provides Jakarta EE 9, Eclipse Jetty 12, Spring Security 6, and Java 17.
* Update plugin pom and baseline
* Remove deprecations
* Use Java 17 language features
* Minor cleanup
`mvn clean verify`
> Require Jenkins 2.479.3 or newer and Jakarta EE 9
